### ISSUE TITLE
Server酱正收到你输入的链接啦！(◍•ᴗ•◍) 正在努力处理中，请稍等片刻...

### ISSUE THREAD

**Issue by x-lcx** [Evil0ctal/Douyin_TikTok_Download_API#169]
最近两天会一直卡在
Server酱正收到你输入的链接啦！(◍•ᴗ•◍)
正在努力处理中，请稍等片刻...

前天开始出现这个问题 版本是V3.1.5。
当时使用douyin.wtf也会遇到相同问题，
更新V3.1.6后依然无法使用.

**Comment by Evil0ctal** [comment]
已经修复了。

**Comment by x-lcx** [comment]
大佬你好， 我是用docker部署的 已经更新到最新版本 但是问题依然存在
麻烦大佬帮忙看看

  File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/app/scraper.py", line 290, in get_douyin_video_data
    raise e
  File "/app/scraper.py", line 275, in get_douyin_video_data
    api_url = self.generate_x_bogus_url(api_url)
  File "/app/scraper.py", line 221, in generate_x_bogus_url
    xbogus = execjs.compile(open('./X-Bogus.js').read()).call('sign', query, self.headers['User-Agent'])
  File "/root/.local/lib/python3.10/site-packages/execjs/__init__.py", line 61, in compile
    return get().compile(source, cwd)
  File "/root/.local/lib/python3.10/site-packages/execjs/_runtimes.py", line 21, in get
    return get_from_environment() or _find_available_runtime()
  File "/root/.local/lib/python3.10/site-packages/execjs/_runtimes.py", line 49, in _find_available_runtime
    raise exceptions.RuntimeUnavailableError("Could not find an available JavaScript runtime.")
execjs._exceptions.RuntimeUnavailableError: Could not find an available JavaScript runtime.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 330, in _invoke_callbacks
    callback(self)
  File "/root/.local/lib/python3.10/site-packages/pywebio/session/coroutinebased.py", line 347, in _wakeup
    self.step(future.result())
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/app/scraper.py", line 454, in hybrid_parsing
    data = await self.get_douyin_video_data(
  File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/root/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f6a844da710 state=finished raised RuntimeUnavailableError>]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/app/scraper.py", line 290, in get_douyin_video_data
    raise e
  File "/app/scraper.py", line 275, in get_douyin_video_data
    api_url = self.generate_x_bogus_url(api_url)
  File "/app/scraper.py", line 221, in generate_x_bogus_url
    xbogus = execjs.compile(open('./X-Bogus.js').read()).call('sign', query, self.headers['User-Agent'])
  File "/root/.local/lib/python3.10/site-packages/execjs/__init__.py", line 61, in compile
    return get().compile(source, cwd)
  File "/root/.local/lib/python3.10/site-packages/execjs/_runtimes.py", line 21, in get
    return get_from_environment() or _find_available_runtime()
  File "/root/.local/lib/python3.10/site-packages/execjs/_runtimes.py", line 49, in _find_available_runtime
    raise exceptions.RuntimeUnavailableError("Could not find an available JavaScript runtime.")
execjs._exceptions.RuntimeUnavailableError: Could not find an available JavaScript runtime.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/root/.local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/root/.local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/.local/lib/python3.10/site-packages/slowapi/extension.py", line 729, in async_wrapper
    response = await func(*args, **kwargs)  # type: ignore
  File "/app/web_api.py", line 267, in hybrid_parsing
    data = await api.hybrid_parsing(url)
  File "/app/scraper.py", line 454, in hybrid_parsing
    data = await self.get_douyin_video_data(
  File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/root/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7fe57262a140 state=finished raised RuntimeUnavailableError>]

**Comment by Evil0ctal** [comment]
Docker还没来得及更新，你们需要安装NodeJS环境。

**Comment by Evil0ctal** [comment]
我刚刚更新了Dockerfile，重新部署一下。

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/blob/main/Dockerfile

**Comment by 1amfine2333** [comment]
老哥，用了docker hub最新的，出来了新的报错，是有nodejs的版本

`exception calling callback for <Future at 0x7f3dc94218d0 state=finished raised RetryError>
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/app/scraper.py", line 290, in get_douyin_video_data
    raise e
  File "/app/scraper.py", line 275, in get_douyin_video_data
    api_url = self.generate_x_bogus_url(api_url)
  File "/app/scraper.py", line 221, in generate_x_bogus_url
    xbogus = execjs.compile(open('./X-Bogus.js').read()).call('sign', query, self.headers['User-Agent'])
  File "/root/.local/lib/python3.10/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "/root/.local/lib/python3.10/site-packages/execjs/_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "/root/.local/lib/python3.10/site-packages/execjs/_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "/root/.local/lib/python3.10/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/root/.local/lib/python3.10/site-packages/execjs/_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "/root/.local/lib/python3.10/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 330, in _invoke_callbacks
    callback(self)
  File "/root/.local/lib/python3.10/site-packages/pywebio/session/coroutinebased.py", line 347, in _wakeup
    self.step(future.result())
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/app/scraper.py", line 454, in hybrid_parsing
    data = await self.get_douyin_video_data(
  File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/root/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f3dc9421150 state=finished raised ProgramError>]
`

**Comment by Evil0ctal** [comment]
不确定这个是什么情况，我晚点去复现一下，如果其他人在使用docker部署时也有这个问题请告诉我。

**Comment by fgprodigal** [comment]
同样的问题，最新的镜像

**Comment by liunice** [comment]
我发现docker.io上的镜像还是半年以前的？好像并没有更新啊，也难怪解析时会报错~

**Comment by jw-star** [comment]
> 我晚点去复现一下，如果其他人在使用docker部署时也有这个问题请告诉我。

我现在看下

**Comment by dzplus** [comment]
oh shit 我也遇到这个问题了  刚才没注意这个帖子里已经提到这个情况

**Comment by Evil0ctal** [comment]
你们再去试一下，我重新修改了一下Dockerfile

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/blob/main/Dockerfile

**Comment by jw-star** [comment]
@Evil0ctal  自动编译没通过，报错了

**Comment by Evil0ctal** [comment]
@jw-star 再去试一下看看

**Comment by Evil0ctal** [comment]
你们可以参考一下`install.sh`，如果可以的话可以PR一份Dockerfile到仓库里。

https://raw.githubusercontent.com/Evil0ctal/Douyin_TikTok_Download_API/main/bash/install.sh

**Comment by fgprodigal** [comment]
```
douyin_tiktok_download_api  | exception calling callback for <Future at 0x7f6036f198d0 state=finished raised RetryError>
douyin_tiktok_download_api  | Traceback (most recent call last):
douyin_tiktok_download_api  |   File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
douyin_tiktok_download_api  |     result = await fn(*args, **kwargs)
douyin_tiktok_download_api  |   File "/app/scraper.py", line 290, in get_douyin_video_data
douyin_tiktok_download_api  |     raise e
douyin_tiktok_download_api  |   File "/app/scraper.py", line 275, in get_douyin_video_data
douyin_tiktok_download_api  |     api_url = self.generate_x_bogus_url(api_url)
douyin_tiktok_download_api  |   File "/app/scraper.py", line 221, in generate_x_bogus_url
douyin_tiktok_download_api  |     xbogus = execjs.compile(open('./X-Bogus.js').read()).call('sign', query, self.headers['User-Agent'])
douyin_tiktok_download_api  |   File "/root/.local/lib/python3.10/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
douyin_tiktok_download_api  |     return self._call(name, *args)
douyin_tiktok_download_api  |   File "/root/.local/lib/python3.10/site-packages/execjs/_external_runtime.py", line 92, in _call
douyin_tiktok_download_api  |     return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
douyin_tiktok_download_api  |   File "/root/.local/lib/python3.10/site-packages/execjs/_external_runtime.py", line 78, in _eval
douyin_tiktok_download_api  |     return self.exec_(code)
douyin_tiktok_download_api  |   File "/root/.local/lib/python3.10/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
douyin_tiktok_download_api  |     return self._exec_(source)
douyin_tiktok_download_api  |   File "/root/.local/lib/python3.10/site-packages/execjs/_external_runtime.py", line 88, in _exec_
douyin_tiktok_download_api  |     return self._extract_result(output)
douyin_tiktok_download_api  |   File "/root/.local/lib/python3.10/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
douyin_tiktok_download_api  |     raise ProgramError(value)
douyin_tiktok_download_api  | execjs._exceptions.ProgramError: TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null
douyin_tiktok_download_api  |
douyin_tiktok_download_api  | The above exception was the direct cause of the following exception:
douyin_tiktok_download_api  |
douyin_tiktok_download_api  | Traceback (most recent call last):
douyin_tiktok_download_api  |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 330, in _invoke_callbacks
douyin_tiktok_download_api  |     callback(self)
douyin_tiktok_download_api  |   File "/root/.local/lib/python3.10/site-packages/pywebio/session/coroutinebased.py", line 347, in _wakeup
douyin_tiktok_download_api  |     self.step(future.result())
douyin_tiktok_download_api  |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result
douyin_tiktok_download_api  |     return self.__get_result()
douyin_tiktok_download_api  |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
douyin_tiktok_download_api  |     raise self._exception
douyin_tiktok_download_api  |   File "/app/scraper.py", line 454, in hybrid_parsing
douyin_tiktok_download_api  |     data = await self.get_douyin_video_data(
douyin_tiktok_download_api  |   File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
douyin_tiktok_download_api  |     return await fn(*args, **kwargs)
douyin_tiktok_download_api  |   File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 47, in __call__
douyin_tiktok_download_api  |     do = self.iter(retry_state=retry_state)
douyin_tiktok_download_api  |   File "/root/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
douyin_tiktok_download_api  |     raise retry_exc from fut.exception()
douyin_tiktok_download_api  | tenacity.RetryError: RetryError[<Future at 0x7f6036f1a290 state=finished raised ProgramError>]
```

依然报错

**Comment by jw-star** [comment]
@Evil0ctal  linux上 直接测试scraper.py 都有问题

**Comment by jw-star** [comment]
看来还是缺少 node运行 我安装后正常
apt-get install nodejs

**Comment by jw-star** [comment]
我再看看吧

**Comment by Evil0ctal** [comment]
嗯嗯，参考自述文档：

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/blob/main/README.md#%E9%83%A8%E7%BD%B2%E6%96%B9%E5%BC%8F%E4%B8%80-linux

**Comment by hbyxzpf** [comment]
@Evil0ctal  docker的node 装的版本太低了. 我容器内升级到最新之后就可以了..但是另外一个问题出现了.. Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https

**Comment by Evil0ctal** [comment]
很奇怪，你们可以试一下使用Ubuntu22作为容器的OS吗？

**Comment by jw-star** [comment]
@Evil0ctal  ubuntu 可以，稍等，我提交下

**Comment by jw-star** [comment]
已pr

**Comment by Evil0ctal** [comment]
好的，已经merge了，Thanks♪(･ω･)ﾉ

**Comment by hbyxzpf** [comment]
@jw-star FROM python:3.10.5-slim-buster
MAINTAINER evil0ctal (https://hub.docker.com/repository/docker/evil0ctal/douyin_tiktok_download_api/general)
RUN sed -i "s@http://deb.debian.org@http://mirrors.cloud.tencent.com@g" /etc/apt/sources.list && rm -rf /var/lib/apt/lists/*
RUN apt-get update
RUN apt-get -y install gcc curl && curl -sL https://deb.nodesource.com/setup_19.x | bash -
RUN apt-get -y install nodejs
COPY . /app
RUN pip3 --no-cache-dir install --user -r /app/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
WORKDIR /app
# -u print打印出来

RUN chmod +x start.sh

CMD ["./start.sh"]
 我是这么写的.

**Comment by x-lcx** [comment]
感谢大佬
