### ISSUE TITLE
[BUG] 获取抖音视频数据失败！Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8'

### ISSUE THREAD

**Issue by a13cde** [Evil0ctal/Douyin_TikTok_Download_API#171]
昨天还好好的,今天就不行了

生成的X-Bogus签名为: DFSzswSLResANJ96taVb9t9WcBnV
正在获取视频数据API: https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7139750399879187744&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Evil0ctal&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=128&device_memory=2333&platform=PC&webid=7158288523463362079&X-Bogus=DFSzswSLResANJ96taVb9t9WcBnV
获取抖音视频数据失败！原因:0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8'

Traceback (most recent call last):
  File "C:\Users\a\.virtualenvs\Douyin_Tiktok_Scraper_PyPi\lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "C:\PycharmProjects\Douyin_Tiktok_Scraper_PyPi\douyin_tiktok_scraper\scraper.py", line 295, in get_douyin_video_data
    raise e
  File "C:\PycharmProjects\Douyin_Tiktok_Scraper_PyPi\douyin_tiktok_scraper\scraper.py", line 286, in get_douyin_video_data
    response = await response.json()
  File "C:\Users\a\.virtualenvs\Douyin_Tiktok_Scraper_PyPi\lib\site-packages\aiohttp\client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7139750399879187744&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Evil0ctal&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=128&device_memory=2333&platform=PC&webid=7158288523463362079&X-Bogus=DFSzswSLResANJ96taVb9t9WcBnV')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PycharmProjects\Douyin_Tiktok_Scraper_PyPi\demos\demo.py", line 44, in <module>
    asyncio.run(async_test(url=url))
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\PycharmProjects\Douyin_Tiktok_Scraper_PyPi\demos\demo.py", line 23, in async_test
    douyin_data = await api.get_douyin_video_data(douyin_id)
  File "C:\Users\a\.virtualenvs\Douyin_Tiktok_Scraper_PyPi\lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "C:\Users\a\.virtualenvs\Douyin_Tiktok_Scraper_PyPi\lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\a\.virtualenvs\Douyin_Tiktok_Scraper_PyPi\lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x2168e7478b0 state=finished raised ContentTypeError>]

**Comment by Evil0ctal** [comment]
修复了
