### ISSUE TITLE
[BUG] TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null

### ISSUE THREAD

**Issue by junbrave1** [Evil0ctal/Douyin_TikTok_Download_API#173]
获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null
正在获取抖音视频数据...
获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null
正在获取抖音视频数据...
获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null
正在获取抖音视频数据...
获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/root/douyin/Douyin_TikTok_Download_API/scraper.py", line 291, in get_douyin_video_data
    raise e
  File "/root/douyin/Douyin_TikTok_Download_API/scraper.py", line 276, in get_douyin_video_data
    api_url = self.generate_x_bogus_url(api_url)
  File "/root/douyin/Douyin_TikTok_Download_API/scraper.py", line 222, in generate_x_bogus_url
    xbogus = execjs.compile(open('./X-Bogus.js').read()).call('sign', query, self.headers['User-Agent'])
  File "/usr/local/lib/python3.8/dist-packages/execjs/_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "/usr/local/lib/python3.8/dist-packages/execjs/_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "/usr/local/lib/python3.8/dist-packages/execjs/_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "/usr/local/lib/python3.8/dist-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/usr/local/lib/python3.8/dist-packages/execjs/_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "/usr/local/lib/python3.8/dist-packages/execjs/_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null

The above exception was the direct cause of the following exception:

**Comment by junbrave1** [comment]
部署后运行报这个错如何解决呀  X-Bogus.js中报的错

**Comment by Evil0ctal** [comment]
请参考 #169

部署时使用Ubuntu系统作为运行环境。

**Comment by junbrave1** [comment]
感谢，确实是node版本较低，已经解决！

**Comment by Evil0ctal** [comment]
不客气
