### ISSUE TITLE
[BUG] 最新版本报错

### ISSUE THREAD

**Issue by xxccll** [Evil0ctal/Douyin_TikTok_Download_API#175]
***发生错误的平台？***

如：抖音

***发生错误的端点？***

如：/douyin_video_data/

***提交的输入值？***

如：video_id=7206199797466926348

***是否有再次尝试？***

如：是，发生错误后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

如：有，并且很确定该问题是程序导致的。

SGI application
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/app/scraper.py", line 290, in get_douyin_video_data
    raise e
  File "/app/scraper.py", line 281, in get_douyin_video_data
    response = await response.json()
  File "/root/.local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7206199797466926348&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK&X-Bogus=DFSzswSL15JANJ96taTfq09WcBrm')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/root/.local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/root/.local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/.local/lib/python3.10/site-packages/slowapi/extension.py", line 729, in async_wrapper
    response = await func(*args, **kwargs)  # type: ignore
  File "/app/web_api.py", line 337, in get_douyin_video_data
    video_data = await api.get_douyin_video_data(video_id=video_id)
  File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/root/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7fbea4a074c0 state=finished raised ContentTypeError>]

**Comment by Evil0ctal** [comment]
再试试。

**Comment by xxccll** [comment]
现在好了, 这个是什么原因导致的

**Comment by Evil0ctal** [comment]
cookie需要注册，我已经重新注册了，无需修改代码。

**Comment by xxccll** [comment]
好的

**Comment by xxccll** [comment]
这个情况又出现了, 请问这个故障在什么情况下会出现呢,

**Comment by Evil0ctal** [comment]
已修复，可以自己手动修改scraper.py的cookie修复。

**Comment by xxccll** [comment]
> 已修复，可以自己手动修改scraper.py的cookie修复。

我是用docker部署的,而且我不会python...可咋整 t_t

**Comment by xxccll** [comment]
> 已修复，可以自己手动修改scraper.py的cookie修复。

可否考虑给docker添加一个启动参数,指向这个cookie,这样失效了之后我自己手动重启docker并且传进去cookie?
