### ISSUE TITLE
[BUG] 调用scraper.py中get_douyin_video_data方法报错，ReferenceError: Can't find variable: module”_

### ISSUE THREAD

**Issue by roger68** [Evil0ctal/Douyin_TikTok_Download_API#228]
**抖音平台，直接调用scraper.py中get_douyin_video_data方法报错：**

**调用方法：**
`async def hybrid_parsing(_douyin_url: str) -> dict:
    api = Scraper()
    print("正在测试异步获取抖音视频ID方法...")
    douyin_id = await api.get_douyin_video_id(_douyin_url)
    print("正在测试异步获取抖音视频数据方法...")
    douyin_data = await api.get_douyin_video_data(douyin_id)

asyncio.run(hybrid_parsing(_douyin_url=input("Paste Douyin share URL here: ")))
`

**_报错信息：“获取抖音视频数据失败！原因:ReferenceError: Can't find variable: module”_**

分析了一下，是generate_x_bogus_url方法中这行  xbogus = execjs.compile(open('./X-Bogus.js').read()).call('sign', query, self.headers['User-Agent']) 代码执行出错，但是不知道具体原因。

**以下是详细的日志：**
rogerdeMBP:Douyin_TikTok_Download_API-main roger$ python3 scraper.py 
Paste Douyin share URL here:  7.43 pda:/ 让你在几秒钟之内记住我  https://v.douyin.com/L5pbfdP/ 复制此链接，打开Dou音搜索，直接观看视频！
正在测试异步获取抖音视频ID方法...
正在通过抖音分享链接获取原始链接...
获取原始链接成功, 原始链接为: https://www.iesdouyin.com/share/video/6914948781100338440/
获取到的抖音视频ID为: 6914948781100338440
正在测试异步获取抖音视频数据方法...
正在获取抖音视频数据...
device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=6914948781100338440&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK
获取抖音视频数据失败！原因:ReferenceError: Can't find variable: module
正在获取抖音视频数据...
device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=6914948781100338440&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK
获取抖音视频数据失败！原因:ReferenceError: Can't find variable: module
正在获取抖音视频数据...
device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=6914948781100338440&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK
获取抖音视频数据失败！原因:ReferenceError: Can't find variable: module
正在获取抖音视频数据...
device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=6914948781100338440&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK
获取抖音视频数据失败！原因:ReferenceError: Can't find variable: module
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/Users/roger/Downloads/douyin/Douyin_TikTok_Download_API-main/scraper.py", line 298, in get_douyin_video_data
    raise e
  File "/Users/roger/Downloads/douyin/Douyin_TikTok_Download_API-main/scraper.py", line 280, in get_douyin_video_data
    api_url = self.generate_x_bogus_url(api_url)
  File "/Users/roger/Downloads/douyin/Douyin_TikTok_Download_API-main/scraper.py", line 224, in generate_x_bogus_url
    xbogus = execjs.compile(open('./X-Bogus.js').read()).call('sign', query, self.headers['User-Agent'])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/execjs/_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/execjs/_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/execjs/_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: ReferenceError: Can't find variable: module

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/roger/Downloads/douyin/Douyin_TikTok_Download_API-main/scraper.py", line 685, in <module>
    asyncio.run(hybrid_parsing(_douyin_url=input("Paste Douyin share URL here: ")))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/roger/Downloads/douyin/Douyin_TikTok_Download_API-main/scraper.py", line 679, in hybrid_parsing
    douyin_data = await api.get_douyin_video_data(douyin_id)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x10e393430 state=finished raised ProgramError>]

![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/4043193/a07d1da7-b30a-4166-b943-935dba62123c)

**Comment by Evil0ctal** [comment]
我这边好像无法复现这个问题，有尝试过更换IP或使用代理进行请求吗？

**Comment by roger68** [comment]
> 我这边好像无法复现这个问题，有尝试过更换IP或使用代理进行请求吗？

确实是环境的原因导致的，电脑没有安装node，安装v18.16.1版本以后问题解决。

**Comment by Evil0ctal** [comment]
好的👍🏻👍🏻👍🏻
