### ISSUE TITLE
[BUG] 使用docker部署后，报错

### ISSUE THREAD

**Issue by lifei6671** [Evil0ctal/Douyin_TikTok_Download_API#246]
理论上不应该出现端口冲突的问题，我看配置里面web_api用的事8000，而web_app用的事80.
```
INFO:     Will watch for changes in these directories: ['/app']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [7] using StatReload
Traceback (most recent call last):
  File "/app/web_app.py", line 398, in <module>
    start_server(main, port=port, debug=False, cdn=cdn)
  File "/root/.local/lib/python3.10/site-packages/pywebio/platform/tornado.py", line 291, in start_server
    _, port = _setup_server(webio_handler=handler, port=port, host=host, static_dir=static_dir,
  File "/root/.local/lib/python3.10/site-packages/pywebio/platform/tornado.py", line 205, in _setup_server
    server = app.listen(port, address=host, max_buffer_size=max_buffer_size)
  File "/root/.local/lib/python3.10/site-packages/tornado/web.py", line 2134, in listen
    server.listen(
  File "/root/.local/lib/python3.10/site-packages/tornado/tcpserver.py", line 183, in listen
    sockets = bind_sockets(
  File "/root/.local/lib/python3.10/site-packages/tornado/netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
INFO:     Started server process [10]
INFO:     Waiting for application startup.
INFO:     Application startup complete.

```

**Comment by Evil0ctal** [comment]
你好，根据你的上下文，API似乎已经成功运行在8000端口了，但是你Docker容器的80端口似乎已经被使用了，请在容器中查看80端口被哪个进程占用，或将web_app.py的运行端口在config.ini文件中进行修改，希望这能解决你的问题。

**Comment by lifei6671** [comment]
原来模式是host模式，会占用主机端口。

**Comment by Evil0ctal** [comment]
👍🏻👍🏻👍🏻
