### ISSUE TITLE
[BUG] Cannot read property 'JS_MD5_NO_COMMON_JS' of null

### ISSUE THREAD

**Issue by Caelebs** [Evil0ctal/Douyin_TikTok_Download_API#255]
***Platform where the error occurred?***
`Douyin`

***The endpoint where the error occurred?***
`Web APP`

***Submitted input value?***
`https://v.douyin.com/iJoaujh1/`

***Have you tried again?***
Yes, the error still exists after X time after the error occurred.

***Have you checked the readme or interface documentation for this project?***
Yes, and it is very sure that the problem is caused by the program.

All parsing logs are as follows
```
Use http://10.1.1.2:80/ to access the application
当前链接平台为:douyin
正在获取视频ID...
正在通过抖音分享链接获取原始链接...
获取原始链接成功, 原始链接为: https://www.iesdouyin.com/share/video/7268837076525665596/
获取到的抖音视频ID为: 7268837076525665596
获取视频ID成功,视频ID为:7268837076525665596
正在获取视频数据...
正在获取抖音视频数据...
获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null
正在获取抖音视频数据...
获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null
正在获取抖音视频数据...
获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null
正在获取抖音视频数据...
获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null
exception calling callback for <Future at 0x10b8b3d90 state=finished raised RetryError>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Caelebs/Desktop/Douyin_TikTok_Download_API-main/scraper.py", line 268, in get_douyin_video_data
    raise e
  File "/Users/Caelebs/Desktop/Douyin_TikTok_Download_API-main/scraper.py", line 253, in get_douyin_video_data
    api_url = self.generate_x_bogus_url(api_url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Caelebs/Desktop/Douyin_TikTok_Download_API-main/scraper.py", line 199, in generate_x_bogus_url
    xbogus = execjs.compile(open('./X-Bogus.js').read()).call('sign', query, self.headers['User-Agent'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/execjs/_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/execjs/_external_runtime.py", line 78, in _eval
    return self.exec_(code)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/execjs/_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pywebio/session/coroutinebased.py", line 347, in _wakeup
    self.step(future.result())
              ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/Caelebs/Desktop/Douyin_TikTok_Download_API-main/scraper.py", line 432, in hybrid_parsing
    data = await self.get_douyin_video_data(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x10b497d90 state=finished raised ProgramError>]
```

**Comment by Evil0ctal** [comment]
Make sure you have JavaScript runtime and try deploying this project on Ubuntu.
