### ISSUE TITLE
[BUG] Can't download video from douyin

### ISSUE THREAD

**Issue by nhannguyentrong** [Evil0ctal/Douyin_TikTok_Download_API#313]
I use the sample python code, then return the follow error when download the video

URL: https://www.douyin.com/video/6914948781100338440
ERROR
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jame/Code/home/video/download.py", line 12, in <module>
    asyncio.run(hybrid_parsing(url=input("Paste Douyin/TikTok/Bilibili share URL here: ")))
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/jame/Code/home/video/download.py", line 8, in hybrid_parsing
    result = await api.hybrid_parsing(url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jame/.local/share/virtualenvs/video-hF2q1l9e/lib/python3.11/site-packages/douyin_tiktok_scraper/scraper.py", line 467, in hybrid_parsing
    data = await self.get_douyin_video_data(video_id) if url_platform == 'douyin' \
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jame/.local/share/virtualenvs/video-hF2q1l9e/lib/python3.11/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jame/.local/share/virtualenvs/video-hF2q1l9e/lib/python3.11/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jame/.local/share/virtualenvs/video-hF2q1l9e/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x103763b90 state=finished raised ValueError>]

**Comment by nhannguyentrong** [comment]
More output
(video) ➜  video python download.py
Paste Douyin/TikTok/Bilibili share URL here: https://www.douyin.com/video/7296709661712026918
正在解析**douyin**视频链接...
该链接为原始链接,无需转换,原始链接为: https://www.douyin.com/video/7296709661712026918
获取到的**douyin**视频ID是7296709661712026918
正在请求抖音视频API: https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7296709661712026918&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK&X-Bogus=DFSzswSL97iANnEftFA7L09WcBrm
正在请求抖音视频API: https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7296709661712026918&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK&X-Bogus=DFSzswSL97iANnEftFAN5U9WcBjI
正在请求抖音视频API: https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7296709661712026918&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK&X-Bogus=DFSzswSL97iANnEftFANRU9WcBjA
正在请求抖音视频API: https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7296709661712026918&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK&X-Bogus=DFSzswSL97iANnEftFANAz9WcBjh
Traceback (most recent call last):
  File "/Users/jame/.local/share/virtualenvs/video-hF2q1l9e/lib/python3.11/site-packages/douyin_tiktok_scraper/scraper.py", line 286, in get_douyin_video_data
    response = await response.json()
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jame/.local/share/virtualenvs/video-hF2q1l9e/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1105, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7296709661712026918&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK&X-Bogus=DFSzswSL97iANnEftFANAz9WcBjh')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jame/.local/share/virtualenvs/video-hF2q1l9e/lib/python3.11/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jame/.local/share/virtualenvs/video-hF2q1l9e/lib/python3.11/site-packages/douyin_tiktok_scraper/scraper.py", line 293, in get_douyin_video_data
    raise ValueError(f"获取抖音视频数据出错了: {e}")
ValueError: 获取抖音视频数据出错了: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7296709661712026918&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK&X-Bogus=DFSzswSL97iANnEftFANAz9WcBjh')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jame/Code/home/video/download.py", line 12, in <module>
    asyncio.run(hybrid_parsing(url=input("Paste Douyin/TikTok/Bilibili share URL here: ")))
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/jame/Code/home/video/download.py", line 8, in hybrid_parsing
    result = await api.hybrid_parsing(url)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jame/.local/share/virtualenvs/video-hF2q1l9e/lib/python3.11/site-packages/douyin_tiktok_scraper/scraper.py", line 467, in hybrid_parsing
    data = await self.get_douyin_video_data(video_id) if url_platform == 'douyin' \
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jame/.local/share/virtualenvs/video-hF2q1l9e/lib/python3.11/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jame/.local/share/virtualenvs/video-hF2q1l9e/lib/python3.11/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jame/.local/share/virtualenvs/video-hF2q1l9e/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x106e11390 state=finished raised ValueError>]

**Comment by Smecta** [comment]
<img width="782" alt="image" src="https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/30615458/6e014b9b-2115-4d3d-a16a-4db34fb4bfce">
同样出错了

**Comment by irenemaryanne2** [comment]
Same error with douyin,  exception ends with
`raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x106e11390 state=finished raised ValueError>]`

Tiktok works fine

**Comment by fanlushuai** [comment]
凉了

**Comment by androidformax** [comment]
Did you find a solution?

**Comment by Evil0ctal** [comment]
Please use a dynamic proxy with your own cookie, all code should be work when you replace above parameters.
