### ISSUE TITLE
[BUG] 部署成功了，但是出现一堆错误，说的是js，我的环境是本地的python搭建。请看如下

### ISSUE THREAD

**Issue by 1487879421888** [Evil0ctal/Douyin_TikTok_Download_API#345]
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/47622641/e1b443db-ef83-47c5-a20e-5b6da1423462)

正在解析**douyin**视频链接...
正在通过抖音分享链接获取原始链接...
获取原始链接成功, 原始链接为: https://www.iesdouyin.com/share/video/7353625848802561316/
获取到的**douyin**视频ID是7353625848802561316
exception calling callback for <Future at 0x1fded8297d0 state=finished raised RetryError>
Traceback (most recent call last):
  File "D:\pycharm_project\Douyin_TikTok_Download_API-main\scraper.py", line 405, in get_douyin_video_data
    api_url = self.generate_x_bogus_url(api_url, self.douyin_api_headers)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pycharm_project\Douyin_TikTok_Download_API-main\scraper.py", line 145, in generate_x_bogus_url
    xbogus = execjs.compile(open('./X-Bogus.js').read()).call('sign', query, headers['User-Agent'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pycharm_project\Douyin_TikTok_Download_API-main\venv\Lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pycharm_project\Douyin_TikTok_Download_API-main\venv\Lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pycharm_project\Douyin_TikTok_Download_API-main\venv\Lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
           ^^^^^^^^^^^^^^^^
  File "D:\pycharm_project\Douyin_TikTok_Download_API-main\venv\Lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\pycharm_project\Douyin_TikTok_Download_API-main\venv\Lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pycharm_project\Douyin_TikTok_Download_API-main\venv\Lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: 缺少 ';'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pycharm_project\Douyin_TikTok_Download_API-main\venv\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pycharm_project\Douyin_TikTok_Download_API-main\scraper.py", line 417, in get_douyin_video_data
    raise ValueError(f"获取抖音视频数据出错了: {e}")
ValueError: 获取抖音视频数据出错了: SyntaxError: 缺少 ';'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "D:\pycharm_project\Douyin_TikTok_Download_API-main\venv\Lib\site-packages\pywebio\session\coroutinebased.py", line 347, in _wakeup
    self.step(future.result())
              ^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\pycharm_project\Douyin_TikTok_Download_API-main\scraper.py", line 735, in hybrid_parsing
    data = await self.get_douyin_video_data(video_id) if url_platform == 'douyin' \
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pycharm_project\Douyin_TikTok_Download_API-main\venv\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pycharm_project\Douyin_TikTok_Download_API-main\venv\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pycharm_project\Douyin_TikTok_Download_API-main\venv\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1fded856110 state=finished raised ValueError>]

**Comment by Evil0ctal** [comment]
安装nodejs环境

**Comment by 1487879421888** [comment]
> 安装nodejs环境

佬，我已经安装了，我测试接口的时候，就是单文件。还是嘎了。
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/47622641/80d97c9b-7133-47ae-9920-5fae6723180a)

![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/47622641/55e7daf1-c645-4843-9eb2-80f73ee55931)

**Comment by Evil0ctal** [comment]
> 9.74 [g@b.an](mailto:g@b.an) zgO:/ 08/16 可以忙，可以累，但不可以不开心。# 只要有你 [v.douyin.com/iY289sck](https://v.douyin.com/iY289sck/) 复制此链接，打开Dou音搜索，直接观看视频！ 我是这个直接拷贝过去的，但是报错了

手动转换一下链接：https://www.douyin.com/video/7353625848802561316
