### ISSUE TITLE
[BUG] 本地搭建报网络错误, 不太明白该怎么解决

### ISSUE THREAD

**Issue by xyhubl** [Evil0ctal/Douyin_TikTok_Download_API#362]
Traceback (most recent call last):
  File "/Users/mac/pythonsrc/pythonProject/Douyin_TikTok_Download_API/start.py", line 37, in <module>
    from app.main import app
  File "/Users/mac/pythonsrc/pythonProject/Douyin_TikTok_Download_API/app/main.py", line 39, in <module>
    from app.api.router import router as api_router
  File "/Users/mac/pythonsrc/pythonProject/Douyin_TikTok_Download_API/app/api/router.py", line 2, in <module>
    from app.api.endpoints import (
  File "/Users/mac/pythonsrc/pythonProject/Douyin_TikTok_Download_API/app/api/endpoints/tiktok_web.py", line 7, in <module>
    from crawlers.tiktok.web.web_crawler import TikTokWebCrawler  # 导入TikTokWebCrawler类
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/pythonsrc/pythonProject/Douyin_TikTok_Download_API/crawlers/tiktok/web/web_crawler.py", line 55, in <module>
    from crawlers.tiktok.web.models import (
  File "/Users/mac/pythonsrc/pythonProject/Douyin_TikTok_Download_API/crawlers/tiktok/web/models.py", line 10, in <module>
    class BaseRequestModel(BaseModel):
  File "/Users/mac/pythonsrc/pythonProject/Douyin_TikTok_Download_API/crawlers/tiktok/web/models.py", line 43, in BaseRequestModel
    msToken: str = TokenManager.gen_real_msToken()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/pythonsrc/pythonProject/Douyin_TikTok_Download_API/crawlers/tiktok/web/utils.py", line 86, in gen_real_msToken
    raise APIConnectionError("请求端点失败，请检查当前网络环境。 链接：{0}，代理：{1}，异常类名：{2}，异常详细信息：{3}"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
crawlers.utils.api_exceptions.APIConnectionError: 请求端点失败，请检查当前网络环境。 链接：https://mssdk-sg.tiktok.com/web/common?msToken=1Ab-7YxR9lUHSem0PraI_XzdKmpHb6j50L8AaXLAd2aWTdoJCYLfX_67rVQFE4UwwHVHmyG_NfIipqrlLT3kCXps-5PYlNAqtdwEg7TrDyTAfCKyBrOLmhMUjB55oW8SPZ4_EkNxNFUdV7MquA==，代理：{'http://': None, 'https://': None}，异常类名：TokenManager，异常详细信息：timed out
程序出现异常，请检查错误信息。

**Comment by Evil0ctal** [comment]
检查一下你的本地代理试试

**Comment by xyhubl** [comment]
我开了科学上网, 能正常访问google 不太明白额

**Comment by xyhubl** [comment]
解决了 谢谢

**Comment by Evil0ctal** [comment]
代理有时候会导致SSL报错，建议你配置一个软路由来进行翻墙操作。
