### ISSUE TITLE
[BUG] 尬笑.jpg 一个不会python的🧑‍💻在本机运行不起来报错

### ISSUE THREAD

**Issue by qcks** [Evil0ctal/Douyin_TikTok_Download_API#363]
去年在Windos系统跑过一次正常，现在看了readme完全没有之前的使用方式，在这里找到[参考文档](https://hub.docker.com/r/evil0ctal/douyin_tiktok_download_api)
mac m2系统
python --version//Python 3.12.1
python3 --version//Python 3.9.6

```
Traceback (most recent call last):
  File "/Users/user/work/Douyin_TikTok_Download_API/start.py", line 37, in <module>
  from app.main import app, Host_IP, Host_Port
  File "/Users/user/work/Douyin_TikTok_Download_API/app/main.py", line 39, in <module>
  from app.api.router import router as api_router
  File "/Users/user/work/Douyin_TikTok_Download_API/app/api/router.py", line 2, in <module>
  from app.api.endpoints import (
  File "/Users/user/work/Douyin_TikTok_Download_API/app/api/endpoints/tiktok_web.py", line 7, in <module>
  from crawlers.tiktok.web.web_crawler import TikTokWebCrawler  # 导入TikTokWebCrawler类
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/work/Douyin_TikTok_Download_API/crawlers/tiktok/web/web_crawler.py", line 55, in <module>
  from crawlers.tiktok.web.models import (
  File "/Users/user/work/Douyin_TikTok_Download_API/crawlers/tiktok/web/models.py", line 10, in <module>
  class BaseRequestModel(BaseModel):
  File "/Users/user/work/Douyin_TikTok_Download_API/crawlers/tiktok/web/models.py", line 43, in BaseRequestModel
  msToken: str = TokenManager.gen_real_msToken()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/work/Douyin_TikTok_Download_API/crawlers/tiktok/web/utils.py", line 86, in gen_real_msToken
  raise APIConnectionError("请求端点失败，请检查当前网络环境。 链接：{0}，代理：{1}，异常类名：{2}，异常详细信息：{3}"
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
crawlers.utils.api_exceptions.APIConnectionError: 请求端点失败，请检查当前网络环境。 链接：https://mssdk-sg.tiktok.com/web/common?msToken=1Ab-7YxR9lUHSem0PraI_XzdKmpHb6j50L8AaXLAd2aWTdoJCYLfX_67rVQFE4UwwHVHmyG_NfIipqrlLT3kCXps-5PYlNAqtdwEg7TrDyTAfCKyBrOLmhMUjB55oW8SPZ4_EkNxNFUdV7MquA==，代理：{'http://': None, 'https://': None}，异常类名：TokenManager，异常详细信息：timed out


```

**Comment by Evil0ctal** [comment]
你好，这个错误看起来是网络环境造成的，请问你的系统是否在运行什么代理软件？ 如果没有，尝试手动替换成你自己的抖音网站cookie，cookie可以从浏览器的控制台中获取，粘贴到crawler/douyin/web/config.yaml文件中的cookie。

**Comment by Evil0ctal** [comment]
旧版本的文档请在release中下载。

**Comment by xiaotudoushizhenjun** [comment]
我也遇到了这个问题，把网络代理都关了还是不行

**Comment by xiaotudoushizhenjun** [comment]
这个问题我没有解决，但是我把TikTok相关的煮食掉了，本地能启动起来了
![81B47156-821B-41E4-A37E-E78A75D8433D](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/51280856/e7cb3e9a-db8d-482f-98ac-a32c32cb34ba)
![E8871503-8FBD-4286-9A5A-1AC53A71E67F](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/51280856/b9cfe2f0-e4f8-4811-9a83-712f580d354c)

**Comment by Evil0ctal** [comment]
看一下视频教程：

【【开源项目教程】教你一分钟内部署属于你自己的抖音和TikTok数据接口，可以下载视频，做数据分析等。-哔哩哔哩】 https://b23.tv/MTGT71Z
