### ISSUE TITLE
[BUG] 国内服务器报错提示 疑似无法访问TikTok服务导致

### ISSUE THREAD

**Issue by kiko923** [Evil0ctal/Douyin_TikTok_Download_API#368]
Traceback (most recent call last):
File "/app/start.py", line 37, in <module>
from app.main import app, Host_IP, Host_Port
File "/app/app/main.py", line 39, in <module>
from app.api.router import router as api_router
File "/app/app/api/router.py", line 2, in <module>
from app.api.endpoints import (
File "/app/app/api/endpoints/tiktok_web.py", line 7, in <module>
from crawlers.tiktok.web.web_crawler import TikTokWebCrawler # 导入TikTokWebCrawler类
File "/app/crawlers/tiktok/web/web_crawler.py", line 55, in <module>
from crawlers.tiktok.web.models import (
File "/app/crawlers/tiktok/web/models.py", line 10, in <module>
class BaseRequestModel(BaseModel):
File "/app/crawlers/tiktok/web/models.py", line 43, in BaseRequestModel
msToken: str = TokenManager.gen_real_msToken()
File "/app/crawlers/tiktok/web/utils.py", line 86, in gen_real_msToken
raise APIConnectionError("请求端点失败，请检查当前网络环境。 链接：{0}，代理：{1}，异常类名：{2}，异常详细信息：{3}"
crawlers.utils.api_exceptions.APIConnectionError: 请求端点失败，请检查当前网络环境。 链接：https://mssdk-sg.tiktok.com/web/common?msToken=1Ab-7YxR9lUHSem0PraI_XzdKmpHb6j50L8AaXLAd2aWTdoJCYLfX_67rVQFE4UwwHVHmyG_NfIipqrlLT3kCXps-5PYlNAqtdwEg7TrDyTAfCKyBrOLmhMUjB55oW8SPZ4_EkNxNFUdV7MquA==，代理：{'http://': None, 'https://': None}，异常类名：TokenManager，异常详细信息：[Errno 101] Network is unreachable

国内机器会这样报错 香港和美国机器就可以正常用

**Comment by Evil0ctal** [comment]
嗯嗯，这个对国内用户不是很好，我晚点把这部分修改一下。

**Comment by Evil0ctal** [comment]
这个值必须要带，目前没办法修改。

**Comment by kiko923** [comment]
> 这个值必须要带，目前没办法修改。

或者能加个socks5的代理吗 这样也方便一点

**Comment by qcks** [comment]
尬笑 难怪我运行不起来

**Comment by Newbie-L** [comment]
+1，但是我开了全局梯也会报错，就有点奇怪

**Comment by kiko923** [comment]
新版本4.0.1已解决 感谢作者无私奉献 非常感谢
