### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by cslovewl** [Evil0ctal/Douyin_TikTok_Download_API#466]
我启动服务报错，内容如下：

(DouyinDownload) [root@hcss-ecs-0777 Douyin_TikTok_Download_API-4.0.5]# INFO:     Will watch for changes in these directories: ['/opt/Douyin_TikTok_Download_API-4.0.5']
INFO:     Uvicorn running on http://0.0.0.0:8244 (Press CTRL+C to quit)
INFO:     Started reloader process [3207069] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/root/miniconda3/envs/DouyinDownload/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/miniconda3/envs/DouyinDownload/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/DouyinDownload/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/root/miniconda3/envs/DouyinDownload/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/DouyinDownload/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/DouyinDownload/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/DouyinDownload/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/DouyinDownload/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/root/miniconda3/envs/DouyinDownload/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/root/miniconda3/envs/DouyinDownload/lib/python3.12/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/DouyinDownload/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/DouyinDownload/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/Douyin_TikTok_Download_API-4.0.5/app/main.py", line 39, in <module>
    from app.api.router import router as api_router
  File "/opt/Douyin_TikTok_Download_API-4.0.5/app/api/router.py", line 2, in <module>
    from app.api.endpoints import (
  File "/opt/Douyin_TikTok_Download_API-4.0.5/app/api/endpoints/douyin_web.py", line 6, in <module>
    from crawlers.douyin.web.web_crawler import DouyinWebCrawler  # 导入抖音Web爬虫
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Douyin_TikTok_Download_API-4.0.5/crawlers/douyin/web/web_crawler.py", line 46, in <module>
    from crawlers.douyin.web.models import (
  File "/opt/Douyin_TikTok_Download_API-4.0.5/crawlers/douyin/web/models.py", line 4, in <module>
    from crawlers.douyin.web.utils import TokenManager, VerifyFpManager
  File "/opt/Douyin_TikTok_Download_API-4.0.5/crawlers/douyin/web/utils.py", line 78, in <module>
    class TokenManager:
  File "/opt/Douyin_TikTok_Download_API-4.0.5/crawlers/douyin/web/utils.py", line 84, in TokenManager
    "http://": proxies_conf.get("http", None),
               ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

我到Douyin_TikTok_Download_API-4.0.5\crawlers\douyin\web\config.yaml中查看
    proxies:
      http:
      https:
确实都是空的。
但我之前也是空的是能启动成功的啊，不知道现在为什么不行了。求大佬救救孩子

**Comment by Evil0ctal** [comment]
尝试重新clone一下项目

**Comment by cslovewl** [comment]
感谢大佬orz，重新clone以后解决了。

**Comment by Evil0ctal** [comment]
好的 真不错
