### ISSUE TITLE
[Not A BUG] 好像没法解析视频了？更新到最新版且替换了cookie

### ISSUE THREAD

**Issue by blue-cat** [Evil0ctal/Douyin_TikTok_Download_API#491]
***发生错误的平台？***

抖音

***发生错误的端点？***

API-V1/Web APP
我本地部署的没法解析，使用博主的wtf的网页也解析不了

***提交的输入值？***

[如：短视频链接](https://v.douyin.com/CeiH5oqt/)

***是否有再次尝试？***

是，很长时间了

***你有查看本项目的自述文件或接口文档吗？***

有，并且很确定该问题是程序导致的。提示错误：
{"detail":{"code":400,"message":"An error occurred.","support":"Please contact us on Github: https://github.com/Evil0ctal/Douyin_TikTok_Download_API","time":"2024-09-30 01:46:16","router":"/api/hybrid/video_data","params":{"url":"https://v.douyin.com/CeiH5oqt/"}}}

**Comment by a5582323** [comment]
你不是一个人,我昨天试了八十遍,cookie换了8遍

**Comment by Evil0ctal** [comment]
![image](https://github.com/user-attachments/assets/b05edd18-f0e2-4614-a7cc-5268212a5307)

**Comment by Evil0ctal** [comment]
我这边好像没办法复现你们的问题，你们使用的是登录后的Cookie吗？

**Comment by a5582323** [comment]
> 我这边好像没办法复现你们的问题，你们使用的是登录后的Cookie吗？

是登录后的cookie

**Comment by Evil0ctal** [comment]
那有点奇怪了，你看看能不能请求别的接口，如评论，个人主页视频之类的。

**Comment by a5582323** [comment]
> 那有点奇怪了，你看看能不能请求别的接口，如评论，个人主页视频之类的。

![image](https://github.com/user-attachments/assets/9aa259e1-dbfd-4d95-a9ba-5cec9af08f24)
这个接口是OK的

**Comment by a5582323** [comment]
经测试,我本机生成的cookie在本机能正常返回,扔到服务器上就不行了

**Comment by blue-cat** [comment]
重新试了下，用登陆后的cookie还是不行，我一直用的服务器。
以前也是一样的方式拿的cookie是没问题的。
期待作者看看这个问题

**Comment by Evil0ctal** [comment]
我还是没办法复现出这个问题，我使用本机获取cookie之后放到服务器上也是一切正常的，你们放到服务器上之后是否对项目进行了重启操作？

**Comment by xiaojun-ai** [comment]
有些接口可以解析，有些接口不可以。

**Comment by xiaojun-ai** [comment]
有些接口可以解析，有些不可以。

**Comment by lxj0123** [comment]
登录之后获取的cookie有些接口可以解析，有些不行。

**Comment by Evil0ctal** [comment]
> 登录之后获取的cookie有些接口可以解析，有些不行。

哪些不行呢？

**Comment by iJarmin** [comment]
同样遇到了问题，附完整报错信息
```
         zFgf3qJLzMj%3D%3D
程序出现异常，请检查错误信息。
ERROR    无效响应类型。响应类型: <class 'NoneType'>
程序出现异常，请检查错误信息。
INFO:     Shutting down
INFO:     connection closed
INFO:     Finished server process [14104]
ERROR:    Traceback (most recent call last):
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\luca\Downloads\Douyin_TikTok_Download_API-4.0.9\venv\Lib\site-packages\uvicorn\server.py", line 68, in serve
    with self.capture_signals():
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "C:\Users\luca\Downloads\Douyin_TikTok_Download_API-4.0.9\venv\Lib\site-packages\uvicorn\server.py", line 328, in capture_signals
    signal.raise_signal(captured_signal)
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\luca\Downloads\Douyin_TikTok_Download_API-4.0.9\venv\Lib\site-packages\starlette\routing.py", line 741, in lifespan
    await receive()
  File "C:\Users\luca\Downloads\Douyin_TikTok_Download_API-4.0.9\venv\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\luca\Downloads\Douyin_TikTok_Download_API-4.0.9\venv\Lib\site-packages\uvicorn\_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\luca\Downloads\Douyin_TikTok_Download_API-4.0.9\venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\luca\Downloads\Douyin_TikTok_Download_API-4.0.9\venv\Lib\site-packages\uvicorn\server.py", line 68, in serve
    with self.capture_signals():
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "C:\Users\luca\Downloads\Douyin_TikTok_Download_API-4.0.9\venv\Lib\site-packages\uvicorn\server.py", line 328, in capture_signals
    signal.raise_signal(captured_signal)
  File "C:\Users\luca\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt
INFO:     Stopping reloader process [27612]
```

**Comment by jiliangC** [comment]
> 更换Cookie并且不要修改默认config文件中的其他字段，尤其是User Agent

我也是遇到上面的问题，只修改Cookie其他没动，抖音不能，b站可以

**Comment by Evil0ctal** [comment]
我还是没有办法复现出来

**Comment by iHunterDev** [comment]
我目前也遇到了同样的问题，看运行日志是能够正常请求，但是返回为空。

```
INFO:     10.0.1.4:48060 - "GET / HTTP/1.1" 200 OK
WARNING  第 1 次响应内容为空, 状态码: 200,                                      
         URL:https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=w
         ebapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=190
         500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&screen_he
         ight=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Fi
         refox&browser_version=124.0&browser_online=true&engine_name=Gecko&engin
         e_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&devic
         e_memory=8&platform=PC&msToken=&aweme_id=7440749140633472296&a_bogus=xJ
         RZQ5LkDigTgV6h5A%2FLfY3q63jVYmQo0SVkMD2flaDOAg39HMOx9exoSmGvukyjNG%2FpI
         eEjy4hbT3ohrQ2y0Hwf9W0L%2F25ksDSkKl5Q5xSSs1X9eghgJ04qmkt5SMx2RvB-rOXmqh
         ZHKRbp09oHmhK4b1dzFgf3qJLzUj%3D%3D                                     
WARNING  第 2 次响应内容为空, 状态码: 200,                                      
         URL:https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=w
         ebapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=190
         500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&screen_he
         ight=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Fi
         refox&browser_version=124.0&browser_online=true&engine_name=Gecko&engin
         e_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&devic
         e_memory=8&platform=PC&msToken=&aweme_id=7440749140633472296&a_bogus=xJ
         RZQ5LkDigTgV6h5A%2FLfY3q63jVYmQo0SVkMD2flaDOAg39HMOx9exoSmGvukyjNG%2FpI
         eEjy4hbT3ohrQ2y0Hwf9W0L%2F25ksDSkKl5Q5xSSs1X9eghgJ04qmkt5SMx2RvB-rOXmqh
         ZHKRbp09oHmhK4b1dzFgf3qJLzUj%3D%3D                                     
WARNING  第 3 次响应内容为空, 状态码: 200,                                      
         URL:https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=w
         ebapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=190
         500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&screen_he
         ight=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Fi
         refox&browser_version=124.0&browser_online=true&engine_name=Gecko&engin
         e_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&devic
         e_memory=8&platform=PC&msToken=&aweme_id=7440749140633472296&a_bogus=xJ
         RZQ5LkDigTgV6h5A%2FLfY3q63jVYmQo0SVkMD2flaDOAg39HMOx9exoSmGvukyjNG%2FpI
         eEjy4hbT3ohrQ2y0Hwf9W0L%2F25ksDSkKl5Q5xSSs1X9eghgJ04qmkt5SMx2RvB-rOXmqh
         ZHKRbp09oHmhK4b1dzFgf3qJLzUj%3D%3D                                     
程序出现异常，请检查错误信息。
ERROR    无效响应类型。响应类型: <class 'NoneType'> 
```

**Comment by iHunterDev** [comment]
> 我目前也遇到了同样的问题，看运行日志是能够正常请求，但是返回为空。
> 
> ```
> INFO:     10.0.1.4:48060 - "GET / HTTP/1.1" 200 OK
> WARNING  第 1 次响应内容为空, 状态码: 200,                                      
>          URL:https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=w
>          ebapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=190
>          500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&screen_he
>          ight=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Fi
>          refox&browser_version=124.0&browser_online=true&engine_name=Gecko&engin
>          e_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&devic
>          e_memory=8&platform=PC&msToken=&aweme_id=7440749140633472296&a_bogus=xJ
>          RZQ5LkDigTgV6h5A%2FLfY3q63jVYmQo0SVkMD2flaDOAg39HMOx9exoSmGvukyjNG%2FpI
>          eEjy4hbT3ohrQ2y0Hwf9W0L%2F25ksDSkKl5Q5xSSs1X9eghgJ04qmkt5SMx2RvB-rOXmqh
>          ZHKRbp09oHmhK4b1dzFgf3qJLzUj%3D%3D                                     
> WARNING  第 2 次响应内容为空, 状态码: 200,                                      
>          URL:https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=w
>          ebapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=190
>          500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&screen_he
>          ight=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Fi
>          refox&browser_version=124.0&browser_online=true&engine_name=Gecko&engin
>          e_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&devic
>          e_memory=8&platform=PC&msToken=&aweme_id=7440749140633472296&a_bogus=xJ
>          RZQ5LkDigTgV6h5A%2FLfY3q63jVYmQo0SVkMD2flaDOAg39HMOx9exoSmGvukyjNG%2FpI
>          eEjy4hbT3ohrQ2y0Hwf9W0L%2F25ksDSkKl5Q5xSSs1X9eghgJ04qmkt5SMx2RvB-rOXmqh
>          ZHKRbp09oHmhK4b1dzFgf3qJLzUj%3D%3D                                     
> WARNING  第 3 次响应内容为空, 状态码: 200,                                      
>          URL:https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=w
>          ebapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=190
>          500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&screen_he
>          ight=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Fi
>          refox&browser_version=124.0&browser_online=true&engine_name=Gecko&engin
>          e_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&devic
>          e_memory=8&platform=PC&msToken=&aweme_id=7440749140633472296&a_bogus=xJ
>          RZQ5LkDigTgV6h5A%2FLfY3q63jVYmQo0SVkMD2flaDOAg39HMOx9exoSmGvukyjNG%2FpI
>          eEjy4hbT3ohrQ2y0Hwf9W0L%2F25ksDSkKl5Q5xSSs1X9eghgJ04qmkt5SMx2RvB-rOXmqh
>          ZHKRbp09oHmhK4b1dzFgf3qJLzUj%3D%3D                                     
> 程序出现异常，请检查错误信息。
> ERROR    无效响应类型。响应类型: <class 'NoneType'> 
> ```

后续：目前我的已经恢复了，暂时的观察情况来看的话，疑似请求量太多了，风控了，休息一下过一段时间就又能访问了，我在中途也尝试换了 Cookie，换了 Cookie 也没有直接生效，还是时间问题。

**Comment by Evil0ctal** [comment]
大概率是你们的Cookie风控了，今天替换了一下演示站点的抖音网页Cookie，目前一切工作正常，见下图：

![image](https://github.com/user-attachments/assets/21185cfa-9c4b-4efd-8911-3551a158fe23)

**Comment by Sommunii** [comment]
今天遇到了同样的问题，请求用户视频列表正常返回，请求单个视频具体信息报错，后面重新替换了一次配置文件，只替换cookie就正常，不要随便动UA

**Comment by 2547881370** [comment]
> 今天遇到了同样的问题，请求用户视频列表正常返回，请求单个视频具体信息报错，后面重新替换了一次配置文件，只替换cookie就正常，不要随便动UA

后续还有这种问题吗

**Comment by Evil0ctal** [comment]
这个Issue已经超过30天没有进一步的讨论了，暂时关闭。
